[advisories]
version = 2
yanked = "warn"
ignore = []

[licenses]
version = 2
confidence-threshold = 0.8

[bans]
multiple-versions = "allow"
wildcards = "warn"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
