[package]
name = "service"
version = "0.2.0"
edition = "2024"

[dependencies]
entity = { path = "../entity" }
tokio = { version = "^1", features = ["macros", "rt"] }
reqwest = { version = "^0.12", features = ["rustls-tls", "cookies", "stream"], default-features = false }
serde = { version = "^1", features = ["derive"] }
serde-xml-rs = "^0.8"
serde_repr = "^0.1"
serde_json = "^1"
anyhow = "^1"
thiserror = "^2"
log = "^0.4"
chrono = "^0.4"
rand = "^0.10"
regex = "^1"
lazy_static = "^1"
futures-util = "^0.3"
zip = "^4"
async-recursion = "^1.1"
strum = { version = "^0.28", features = ["derive"] }
derive_builder = "^0.20"
tower = { version = "^0.5", features = ["util", "limit", "retry"] }
oauth2 = { version = "^5", features = ["reqwest"] }
utoipa = { version = "~4", features = ["actix_extras", "uuid", "chrono", "repr", "debug"] }
md-5 = "^0.11"
hex = "^0.4"
num_cpus = "^1.16"
bigdecimal = { version = "^0.4", features = ["serde-json"] }
redis = { version = "^0.32", features = ["tokio-rustls-comp", "aio"] }

[dependencies.sea-orm]
version = "~1" # sea-orm version
features = [
	"debug-print",
	"runtime-tokio-rustls",
	"sqlx-postgres"
]
