use crate::routes::company::{__path_get_all_companies, __path_get_company_by_id};
use crate::routes::game::{
	__path_get_playmatch_game_by_id, __path_get_playmatch_game_with_relations_by_id,
};
use crate::routes::health::{__path_health, __path_ready};
use crate::routes::identify::{
	__path_identify_game_and_relations, __path_identify_game_with_metadata_ids,
};
use crate::routes::igdb::{
	__path_get_igdb_age_rating_by_id, __path_get_igdb_age_rating_categories_by_ids,
	__path_get_igdb_age_rating_category_by_id,
	__path_get_igdb_age_rating_content_description_type_by_id,
	__path_get_igdb_age_rating_content_description_types_by_ids,
	__path_get_igdb_age_rating_content_description_v2_by_id,
	__path_get_igdb_age_rating_content_descriptions_v2_by_ids,
	__path_get_igdb_age_rating_organization_by_id, __path_get_igdb_age_rating_organizations_by_ids,
	__path_get_igdb_age_ratings_by_ids, __path_get_igdb_alternative_name_by_id,
	__path_get_igdb_alternative_names_by_ids, __path_get_igdb_artwork_by_id,
	__path_get_igdb_artwork_type_by_id, __path_get_igdb_artwork_types_by_ids,
	__path_get_igdb_artworks_by_ids, __path_get_igdb_character_mug_shot_by_id,
	__path_get_igdb_character_mug_shots_by_ids, __path_get_igdb_collection_by_id,
	__path_get_igdb_collections_by_ids, __path_get_igdb_company_size_by_id,
	__path_get_igdb_company_sizes_by_ids, __path_get_igdb_company_status_by_id,
	__path_get_igdb_company_statuses_by_ids, __path_get_igdb_company_type_by_id,
	__path_get_igdb_company_type_histories_by_ids, __path_get_igdb_company_type_history_by_id,
	__path_get_igdb_company_types_by_ids, __path_get_igdb_cover_by_id,
	__path_get_igdb_covers_by_ids, __path_get_igdb_date_format_by_id,
	__path_get_igdb_date_formats_by_ids, __path_get_igdb_entity_type_by_id,
	__path_get_igdb_entity_types_by_ids, __path_get_igdb_external_game_by_id,
	__path_get_igdb_external_game_source_by_id, __path_get_igdb_external_game_sources_by_ids,
	__path_get_igdb_external_games_by_ids, __path_get_igdb_franchise_by_id,
	__path_get_igdb_franchises_by_ids, __path_get_igdb_game_by_id,
	__path_get_igdb_game_release_format_by_id, __path_get_igdb_game_release_formats_by_ids,
	__path_get_igdb_game_status_by_id, __path_get_igdb_game_statuses_by_ids,
	__path_get_igdb_game_time_to_beat_by_id, __path_get_igdb_game_time_to_beats_by_ids,
	__path_get_igdb_game_type_by_id, __path_get_igdb_game_types_by_ids,
	__path_get_igdb_games_by_ids, __path_get_igdb_genre_by_id, __path_get_igdb_genres_by_ids,
	__path_get_igdb_platform_type_by_id, __path_get_igdb_platform_types_by_ids,
	__path_get_igdb_release_date_region_by_id, __path_get_igdb_release_date_regions_by_ids,
	__path_get_igdb_report_by_id, __path_get_igdb_report_type_by_id,
	__path_get_igdb_report_types_by_ids, __path_get_igdb_reports_by_ids,
	__path_get_igdb_website_type_by_id, __path_get_igdb_website_types_by_ids,
	__path_search_igdb_game_by_name,
};
use crate::routes::r#match::{
	__path_manually_match_company, __path_manually_match_game, __path_manually_match_platform,
};
use crate::routes::platform::{__path_get_all_platforms, __path_get_platform_by_id};
use crate::routes::suggestion::{
	__path_approve_suggestion, __path_create_company_suggestion, __path_create_game_suggestion,
	__path_create_platform_suggestion, __path_delete_suggestion, __path_get_all_suggestions,
	__path_get_suggestion_by_id,
};
use crate::routes::user::{
	__path_create_or_get_by_discord_id, __path_get_user, __path_get_user_by_discord_id,
	__path_update_user_permission_level,
};
use service::model::matching::{CompanyOrPlatformMatchRequest, GameMatchRequest};
use service::model::suggestion::{
	CompanyOrPlatformSuggestionRequest, GameSuggestionRequest, Suggestion,
	UpdatedMetadataMatchesFromSuggestionResponse,
};
use service::model::user::{
	CreateOrGetUserRequest, UpdateUserPermissionsRequest, User, UserPermissions,
};
use service::model::{
	AutomaticMatchReason, CompanyMetadataResponse, ExternalMetadata, FailedMatchReason,
	GameAndRelationMatchResult, GameAndRelationsResult, GameMatchType, GameMetadataMatchResult,
	ManualMatchMode, MetadataMatchType, MetadataProvider, PlatformMetadataResponse,
	PlaymatchCompany, PlaymatchDatFile, PlaymatchDatFileImport, PlaymatchGame, PlaymatchGameFile,
	PlaymatchPlatform, PlaymatchSignatureGroup, UpdatedMatchResult,
};
use service::providers::igdb::model::{
	AgeRating, AgeRatingCategory, AgeRatingContentDescriptionType, AgeRatingContentDescriptionV2,
	AgeRatingOrganization, AlternativeName, Artwork, ArtworkType, Character, CharacterGender,
	CharacterMugShot, CharacterSpecies, Collection, CollectionMembership, CollectionMembershipType,
	CollectionRelation, CollectionRelationType, CollectionType, Company, CompanyLogo, CompanySize,
	CompanyStatus, CompanyType, CompanyTypeHistory, CompanyWebsite, Cover, DateFormat, EntityType,
	Event, EventLogo, EventNetwork, ExternalGame, ExternalGameSource, Franchise, Game, GameEngine,
	GameEngineLogo, GameLocalization, GameMode, GameReleaseFormat, GameStatus, GameTimeToBeat,
	GameType, GameVersion, GameVersionFeature, GameVersionFeatureCategory, GameVersionFeatureValue,
	GameVersionFeatureValueEnum, GameVideo, Genre, InvolvedCompany, Keyword, Language,
	LanguageSupport, LanguageSupportType, MultiplayerMode, NetworkType, Platform, PlatformFamily,
	PlatformLogo, PlatformType, PlatformVersion, PlatformVersionCompany,
	PlatformVersionReleaseDate, PlatformWebsite, PlayerPerspective, PopularityPrimitive,
	PopularityType, Region, ReleaseDate, ReleaseDateRegion, ReleaseDateStatus, Report, ReportType,
	Screenshot, Theme, Website, WebsiteType,
};
use utoipa::OpenApi;
use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::openapi::{Components, ComponentsBuilder};

#[derive(OpenApi)]
#[openapi(
	paths(
		health,
		ready,
		identify_game_with_metadata_ids,
		identify_game_and_relations,
		manually_match_game,
		manually_match_company,
		manually_match_platform,
		get_playmatch_game_by_id,
		get_playmatch_game_with_relations_by_id,
		get_suggestion_by_id,
		get_all_suggestions,
		create_game_suggestion,
		create_company_suggestion,
		create_platform_suggestion,
		approve_suggestion,
		delete_suggestion,
		create_or_get_by_discord_id,
		get_user_by_discord_id,
		get_user,
		update_user_permission_level,
		get_igdb_game_by_id,
		get_igdb_games_by_ids,
		search_igdb_game_by_name,
		get_igdb_age_rating_by_id,
		get_igdb_age_ratings_by_ids,
		get_igdb_alternative_name_by_id,
		get_igdb_alternative_names_by_ids,
		get_igdb_artwork_by_id,
		get_igdb_artworks_by_ids,
		get_igdb_collection_by_id,
		get_igdb_collections_by_ids,
		get_igdb_cover_by_id,
		get_igdb_covers_by_ids,
		get_igdb_external_game_by_id,
		get_igdb_external_games_by_ids,
		get_igdb_franchise_by_id,
		get_igdb_franchises_by_ids,
		get_igdb_genre_by_id,
		get_igdb_genres_by_ids,
		get_igdb_age_rating_category_by_id,
		get_igdb_age_rating_categories_by_ids,
		get_igdb_age_rating_content_description_v2_by_id,
		get_igdb_age_rating_content_descriptions_v2_by_ids,
		get_igdb_age_rating_content_description_type_by_id,
		get_igdb_age_rating_content_description_types_by_ids,
		get_igdb_age_rating_organization_by_id,
		get_igdb_age_rating_organizations_by_ids,
		get_igdb_company_status_by_id,
		get_igdb_company_statuses_by_ids,
		get_igdb_date_format_by_id,
		get_igdb_date_formats_by_ids,
		get_igdb_external_game_source_by_id,
		get_igdb_external_game_sources_by_ids,
		get_igdb_game_release_format_by_id,
		get_igdb_game_release_formats_by_ids,
		get_igdb_game_status_by_id,
		get_igdb_game_statuses_by_ids,
		get_igdb_game_type_by_id,
		get_igdb_game_types_by_ids,
		get_igdb_platform_type_by_id,
		get_igdb_platform_types_by_ids,
		get_igdb_release_date_region_by_id,
		get_igdb_release_date_regions_by_ids,
		get_igdb_website_type_by_id,
		get_igdb_website_types_by_ids,
		get_igdb_artwork_type_by_id,
		get_igdb_artwork_types_by_ids,
		get_igdb_character_mug_shot_by_id,
		get_igdb_character_mug_shots_by_ids,
		get_igdb_company_size_by_id,
		get_igdb_company_sizes_by_ids,
		get_igdb_company_type_by_id,
		get_igdb_company_types_by_ids,
		get_igdb_company_type_history_by_id,
		get_igdb_company_type_histories_by_ids,
		get_igdb_entity_type_by_id,
		get_igdb_entity_types_by_ids,
		get_igdb_game_time_to_beat_by_id,
		get_igdb_game_time_to_beats_by_ids,
		get_igdb_report_by_id,
		get_igdb_reports_by_ids,
		get_igdb_report_type_by_id,
		get_igdb_report_types_by_ids,
		get_all_companies,
		get_company_by_id,
		get_all_platforms,
		get_platform_by_id
	),
	components(schemas(
		GameMetadataMatchResult,
		CompanyMetadataResponse,
		PlatformMetadataResponse,
		GameMatchType,
		ExternalMetadata,
		MetadataMatchType,
		ManualMatchMode,
		FailedMatchReason,
		MetadataProvider,
		AutomaticMatchReason,
		AgeRating,
		AgeRatingCategory,
		AgeRatingContentDescriptionType,
		AgeRatingContentDescriptionV2,
		AgeRatingOrganization,
		AlternativeName,
		Artwork,
		ArtworkType,
		Character,
		CharacterGender,
		CharacterMugShot,
		CharacterSpecies,
		Collection,
		CollectionMembership,
		CollectionMembershipType,
		CollectionRelation,
		CollectionRelationType,
		CollectionType,
		Company,
		CompanyLogo,
		CompanySize,
		CompanyStatus,
		CompanyType,
		CompanyTypeHistory,
		CompanyWebsite,
		Cover,
		DateFormat,
		EntityType,
		Event,
		EventLogo,
		EventNetwork,
		ExternalGame,
		ExternalGameSource,
		Franchise,
		Game,
		GameEngine,
		GameEngineLogo,
		GameLocalization,
		GameMode,
		GameReleaseFormat,
		GameStatus,
		GameTimeToBeat,
		GameType,
		GameVersion,
		GameVersionFeature,
		GameVersionFeatureCategory,
		GameVersionFeatureValue,
		GameVersionFeatureValueEnum,
		GameVideo,
		Genre,
		InvolvedCompany,
		Keyword,
		Language,
		LanguageSupport,
		LanguageSupportType,
		MultiplayerMode,
		GameMatchRequest,
		CompanyOrPlatformMatchRequest,
		GameAndRelationMatchResult,
		GameAndRelationsResult,
		PlaymatchCompany,
		PlaymatchGame,
		PlaymatchGameFile,
		PlaymatchPlatform,
		PlaymatchDatFile,
		PlaymatchDatFileImport,
		PlaymatchSignatureGroup,
		GameSuggestionRequest,
		CompanyOrPlatformSuggestionRequest,
		UpdatedMetadataMatchesFromSuggestionResponse,
		Suggestion,
		User,
		UserPermissions,
		CreateOrGetUserRequest,
		UpdateUserPermissionsRequest,
		NetworkType,
		Platform,
		PlatformFamily,
		PlatformLogo,
		PlatformType,
		PlatformVersion,
		PlatformVersionCompany,
		PlatformVersionReleaseDate,
		PlatformWebsite,
		PlayerPerspective,
		PopularityPrimitive,
		PopularityType,
		Region,
		ReleaseDate,
		ReleaseDateRegion,
		ReleaseDateStatus,
		Report,
		ReportType,
		Screenshot,
		Theme,
		UpdatedMatchResult,
		Website,
		WebsiteType
	))
)]
pub struct ApiDoc;

pub fn create_openapi() -> utoipa::openapi::OpenApi {
	let mut openapi = ApiDoc::openapi();

	// Extract existing schemas if already generated
	let existing_components = openapi
		.components
		.take()
		.unwrap_or_else(Components::default);

	// Build new components with security scheme
	let new_components = ComponentsBuilder::from(existing_components)
		.security_scheme(
			"bearer_auth",
			SecurityScheme::Http(
				HttpBuilder::new()
					.scheme(HttpAuthScheme::Bearer)
					.bearer_format("JWT")
					.build(),
			),
		)
		.build();

	// Assign merged components back to OpenAPI doc
	openapi.components = Some(new_components);

	openapi
}
