use crate::routes::company::{__path_get_all_companies, __path_get_company_by_id};
use crate::routes::game::{
	__path_get_playmatch_game_by_id, __path_get_playmatch_game_with_relations_by_id,
};
use crate::routes::health::{__path_health, __path_ready};
use crate::routes::identify::{
	__path_identify_game_and_relations, __path_identify_game_with_metadata_ids,
};
use crate::routes::igdb::{
	__path_get_age_rating_by_id, __path_get_age_ratings_by_ids, __path_get_alternative_name_by_id,
	__path_get_alternative_names_by_ids, __path_get_artwork_by_id, __path_get_artworks_by_ids,
	__path_get_collection_by_id, __path_get_collections_by_ids, __path_get_cover_by_id,
	__path_get_covers_by_ids, __path_get_external_game_by_id, __path_get_external_games_by_ids,
	__path_get_franchise_by_id, __path_get_franchises_by_ids, __path_get_game_by_id,
	__path_get_games_by_ids, __path_get_genre_by_id, __path_get_genres_by_ids,
	__path_search_game_by_name,
};
use crate::routes::r#match::{
	__path_manually_match_company, __path_manually_match_game, __path_manually_match_platform,
};
use crate::routes::platform::{__path_get_all_platforms, __path_get_platform_by_id};
use crate::routes::suggestion::{
	__path_approve_suggestion, __path_create_company_suggestion, __path_create_game_suggestion,
	__path_create_platform_suggestion, __path_delete_suggestion, __path_get_all_suggestions,
	__path_get_suggestion_by_id,
};
use crate::routes::user::{
	__path_create_or_get_by_discord_id, __path_get_user, __path_get_user_by_discord_id,
	__path_update_user_permission_level,
};
use service::metadata::igdb::model::{
	AgeRating, AgeRatingCategory, AgeRatingContentCategory, AgeRatingContentDescription,
	AgeRatingEnum, AlternativeName, Artwork, Character, CharacterGender, CharacterSpecies,
	Collection, CollectionMembership, CollectionMembershipType, CollectionRelation,
	CollectionRelationType, CollectionType, Company, CompanyChangeDateCategory, CompanyLogo,
	CompanyStartDateCategory, CompanyWebsite, CompanyWebsiteCategory, Cover, Event, EventLogo,
	EventNetwork, ExternalGame, ExternalGameCategory, ExternalGameMedia, Franchise, Game,
	GameCategory, GameEngine, GameEngineLogo, GameLocalization, GameMode, GameStatus, GameVersion,
	GameVersionFeature, GameVersionFeatureCategory, GameVersionFeatureValue,
	GameVersionFeatureValueEnum, GameVideo, Genre, InvolvedCompany, Keyword, Language,
	LanguageSupport, LanguageSupportType, MultiplayerMode, NetworkType, Platform, PlatformCategory,
	PlatformFamily, PlatformLogo, PlatformVersion, PlatformVersionCompany,
	PlatformVersionReleaseDate, PlatformVersionReleaseDateCategory,
	PlatformVersionReleaseDateRegion, PlatformWebsite, PlatformWebsiteCategory, PlayerPerspective,
	PopularityPrimitive, PopularitySource, PopularityType, Region, ReleaseDate,
	ReleaseDateCategory, ReleaseDateRegion, ReleaseDateStatus, Screenshot, Theme, WebsiteCategory,
};
use service::model::matching::{CompanyOrPlatformMatchRequest, GameMatchRequest};
use service::model::suggestion::{
	CompanyOrPlatformSuggestionRequest, GameSuggestionRequest, Suggestion,
	UpdatedMetadataMatchesFromSuggestionResponse,
};
use service::model::user::{
	CreateOrGetUserRequest, UpdateUserPermissionsRequest, User, UserPermissions,
};
use service::model::{
	AutomaticMatchReason, CompanyMetadataResponse, ExternalMetadata, FailedMatchReason,
	GameAndRelationMatchResult, GameAndRelationsResult, GameMatchType, GameMetadataMatchResult,
	ManualMatchMode, MatchType, MetadataProvider, PlatformMetadataResponse, PlaymatchCompany,
	PlaymatchDatFile, PlaymatchDatFileImport, PlaymatchGame, PlaymatchGameFile, PlaymatchPlatform,
	PlaymatchSignatureGroup, UpdatedMatchResult,
};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
	paths(
		health,
		ready,
		identify_game_with_metadata_ids,
		identify_game_and_relations,
		manually_match_game,
		manually_match_company,
		manually_match_platform,
		get_playmatch_game_by_id,
		get_playmatch_game_with_relations_by_id,
		get_suggestion_by_id,
		get_all_suggestions,
		create_game_suggestion,
		create_company_suggestion,
		create_platform_suggestion,
		approve_suggestion,
		delete_suggestion,
		create_or_get_by_discord_id,
		get_user_by_discord_id,
		get_user,
		get_game_by_id,
		get_games_by_ids,
		update_user_permission_level,
		search_game_by_name,
		get_age_rating_by_id,
		get_age_ratings_by_ids,
		get_alternative_name_by_id,
		get_alternative_names_by_ids,
		get_artwork_by_id,
		get_artworks_by_ids,
		get_collection_by_id,
		get_collections_by_ids,
		get_cover_by_id,
		get_covers_by_ids,
		get_external_game_by_id,
		get_external_games_by_ids,
		get_franchise_by_id,
		get_franchises_by_ids,
		get_genre_by_id,
		get_genres_by_ids,
		get_all_companies,
		get_company_by_id,
		get_all_platforms,
		get_platform_by_id
	),
	components(schemas(
		GameMetadataMatchResult,
		CompanyMetadataResponse,
		PlatformMetadataResponse,
		GameMatchType,
		ExternalMetadata,
		MatchType,
		ManualMatchMode,
		FailedMatchReason,
		MetadataProvider,
		AutomaticMatchReason,
		AgeRating,
		AgeRatingCategory,
		AgeRatingContentCategory,
		AgeRatingContentDescription,
		AgeRatingEnum,
		AlternativeName,
		Artwork,
		Character,
		CharacterGender,
		CharacterSpecies,
		Collection,
		CollectionMembership,
		CollectionMembershipType,
		CollectionRelation,
		CollectionRelationType,
		CollectionType,
		Company,
		CompanyChangeDateCategory,
		CompanyLogo,
		CompanyStartDateCategory,
		CompanyWebsite,
		CompanyWebsiteCategory,
		Cover,
		Event,
		EventLogo,
		EventNetwork,
		ExternalGame,
		ExternalGameCategory,
		ExternalGameMedia,
		Franchise,
		Game,
		GameCategory,
		GameEngine,
		GameEngineLogo,
		GameLocalization,
		GameMode,
		GameStatus,
		GameVersion,
		GameVersionFeature,
		GameVersionFeatureCategory,
		GameVersionFeatureValue,
		GameVersionFeatureValueEnum,
		GameVideo,
		Genre,
		InvolvedCompany,
		Keyword,
		Language,
		LanguageSupport,
		LanguageSupportType,
		MultiplayerMode,
		GameMatchRequest,
		CompanyOrPlatformMatchRequest,
		GameAndRelationMatchResult,
		GameAndRelationsResult,
		PlaymatchCompany,
		PlaymatchGame,
		PlaymatchGameFile,
		PlaymatchPlatform,
		PlaymatchDatFile,
		PlaymatchDatFileImport,
		PlaymatchSignatureGroup,
		GameSuggestionRequest,
		CompanyOrPlatformSuggestionRequest,
		UpdatedMetadataMatchesFromSuggestionResponse,
		Suggestion,
		User,
		UserPermissions,
		CreateOrGetUserRequest,
		UpdateUserPermissionsRequest,
		NetworkType,
		Platform,
		PlatformCategory,
		PlatformFamily,
		PlatformLogo,
		PlatformVersion,
		PlatformVersionCompany,
		PlatformVersionReleaseDate,
		PlatformVersionReleaseDateCategory,
		PlatformVersionReleaseDateRegion,
		PlatformWebsite,
		PlatformWebsiteCategory,
		PlayerPerspective,
		PopularityPrimitive,
		PopularitySource,
		PopularityType,
		Region,
		ReleaseDate,
		ReleaseDateCategory,
		ReleaseDateRegion,
		ReleaseDateStatus,
		Screenshot,
		Theme,
		UpdatedMatchResult,
		WebsiteCategory
	))
)]
pub struct ApiDoc;
