use crate::routes::company::{__path_get_all_companies, __path_get_company_by_id};
use crate::routes::game::{
	__path_get_playmatch_game_by_id, __path_get_playmatch_game_with_relations_by_id,
};
use crate::routes::health::{__path_health, __path_ready};
use crate::routes::identify::{
	__path_identify_game_and_relations, __path_identify_game_with_metadata_ids,
};
use crate::routes::igdb::{
	__path_get_igdb_age_rating_by_id, __path_get_igdb_age_rating_categories_by_ids,
	__path_get_igdb_age_rating_category_by_id,
	__path_get_igdb_age_rating_content_description_type_by_id,
	__path_get_igdb_age_rating_content_description_types_by_ids,
	__path_get_igdb_age_rating_content_description_v2_by_id,
	__path_get_igdb_age_rating_content_descriptions_v2_by_ids,
	__path_get_igdb_age_rating_organization_by_id, __path_get_igdb_age_rating_organizations_by_ids,
	__path_get_igdb_age_ratings_by_ids, __path_get_igdb_alternative_name_by_id,
	__path_get_igdb_alternative_names_by_ids, __path_get_igdb_artwork_by_id,
	__path_get_igdb_artwork_type_by_id, __path_get_igdb_artwork_types_by_ids,
	__path_get_igdb_artworks_by_ids, __path_get_igdb_character_by_id,
	__path_get_igdb_character_gender_by_id, __path_get_igdb_character_genders_by_ids,
	__path_get_igdb_character_mug_shot_by_id, __path_get_igdb_character_mug_shots_by_ids,
	__path_get_igdb_character_species_by_id, __path_get_igdb_character_species_by_ids,
	__path_get_igdb_characters_by_ids, __path_get_igdb_collection_by_id,
	__path_get_igdb_collection_membership_by_id, __path_get_igdb_collection_membership_type_by_id,
	__path_get_igdb_collection_membership_types_by_ids,
	__path_get_igdb_collection_memberships_by_ids, __path_get_igdb_collection_relation_by_id,
	__path_get_igdb_collection_relation_type_by_id,
	__path_get_igdb_collection_relation_types_by_ids, __path_get_igdb_collection_relations_by_ids,
	__path_get_igdb_collection_type_by_id, __path_get_igdb_collection_types_by_ids,
	__path_get_igdb_collections_by_ids, __path_get_igdb_companies_by_ids,
	__path_get_igdb_company_by_id, __path_get_igdb_company_logo_by_id,
	__path_get_igdb_company_logos_by_ids, __path_get_igdb_company_size_by_id,
	__path_get_igdb_company_sizes_by_ids, __path_get_igdb_company_status_by_id,
	__path_get_igdb_company_statuses_by_ids, __path_get_igdb_company_type_by_id,
	__path_get_igdb_company_type_histories_by_ids, __path_get_igdb_company_type_history_by_id,
	__path_get_igdb_company_types_by_ids, __path_get_igdb_company_website_by_id,
	__path_get_igdb_company_websites_by_ids, __path_get_igdb_cover_by_id,
	__path_get_igdb_covers_by_ids, __path_get_igdb_date_format_by_id,
	__path_get_igdb_date_formats_by_ids, __path_get_igdb_entity_type_by_id,
	__path_get_igdb_entity_types_by_ids, __path_get_igdb_event_by_id,
	__path_get_igdb_event_logo_by_id, __path_get_igdb_event_logos_by_ids,
	__path_get_igdb_event_network_by_id, __path_get_igdb_event_networks_by_ids,
	__path_get_igdb_events_by_ids, __path_get_igdb_external_game_by_id,
	__path_get_igdb_external_game_source_by_id, __path_get_igdb_external_game_sources_by_ids,
	__path_get_igdb_external_games_by_ids, __path_get_igdb_franchise_by_id,
	__path_get_igdb_franchises_by_ids, __path_get_igdb_game_by_id,
	__path_get_igdb_game_engine_by_id, __path_get_igdb_game_engine_logo_by_id,
	__path_get_igdb_game_engine_logos_by_ids, __path_get_igdb_game_engines_by_ids,
	__path_get_igdb_game_localization_by_id, __path_get_igdb_game_localizations_by_ids,
	__path_get_igdb_game_mode_by_id, __path_get_igdb_game_modes_by_ids,
	__path_get_igdb_game_release_format_by_id, __path_get_igdb_game_release_formats_by_ids,
	__path_get_igdb_game_status_by_id, __path_get_igdb_game_statuses_by_ids,
	__path_get_igdb_game_time_to_beat_by_id, __path_get_igdb_game_time_to_beats_by_ids,
	__path_get_igdb_game_type_by_id, __path_get_igdb_game_types_by_ids,
	__path_get_igdb_game_version_by_id, __path_get_igdb_game_version_feature_by_id,
	__path_get_igdb_game_version_feature_value_by_id,
	__path_get_igdb_game_version_feature_values_by_ids,
	__path_get_igdb_game_version_features_by_ids, __path_get_igdb_game_versions_by_ids,
	__path_get_igdb_game_video_by_id, __path_get_igdb_game_videos_by_ids,
	__path_get_igdb_games_by_ids, __path_get_igdb_genre_by_id, __path_get_igdb_genres_by_ids,
	__path_get_igdb_involved_companies_by_ids, __path_get_igdb_involved_company_by_id,
	__path_get_igdb_keyword_by_id, __path_get_igdb_keywords_by_ids, __path_get_igdb_language_by_id,
	__path_get_igdb_language_support_by_id, __path_get_igdb_language_support_type_by_id,
	__path_get_igdb_language_support_types_by_ids, __path_get_igdb_language_supports_by_ids,
	__path_get_igdb_languages_by_ids, __path_get_igdb_multiplayer_mode_by_id,
	__path_get_igdb_multiplayer_modes_by_ids, __path_get_igdb_network_type_by_id,
	__path_get_igdb_network_types_by_ids, __path_get_igdb_platform_by_id,
	__path_get_igdb_platform_families_by_ids, __path_get_igdb_platform_family_by_id,
	__path_get_igdb_platform_logo_by_id, __path_get_igdb_platform_logos_by_ids,
	__path_get_igdb_platform_type_by_id, __path_get_igdb_platform_types_by_ids,
	__path_get_igdb_platform_version_by_id, __path_get_igdb_platform_version_companies_by_ids,
	__path_get_igdb_platform_version_company_by_id,
	__path_get_igdb_platform_version_release_date_by_id,
	__path_get_igdb_platform_version_release_dates_by_ids,
	__path_get_igdb_platform_versions_by_ids, __path_get_igdb_platform_website_by_id,
	__path_get_igdb_platform_websites_by_ids, __path_get_igdb_platforms_by_ids,
	__path_get_igdb_player_perspective_by_id, __path_get_igdb_player_perspectives_by_ids,
	__path_get_igdb_popularity_primitive_by_id, __path_get_igdb_popularity_primitives_by_ids,
	__path_get_igdb_popularity_type_by_id, __path_get_igdb_popularity_types_by_ids,
	__path_get_igdb_region_by_id, __path_get_igdb_regions_by_ids,
	__path_get_igdb_release_date_by_id, __path_get_igdb_release_date_region_by_id,
	__path_get_igdb_release_date_regions_by_ids, __path_get_igdb_release_date_status_by_id,
	__path_get_igdb_release_date_statuses_by_ids, __path_get_igdb_release_dates_by_ids,
	__path_get_igdb_report_by_id, __path_get_igdb_report_type_by_id,
	__path_get_igdb_report_types_by_ids, __path_get_igdb_reports_by_ids,
	__path_get_igdb_screenshot_by_id, __path_get_igdb_screenshots_by_ids,
	__path_get_igdb_theme_by_id, __path_get_igdb_themes_by_ids, __path_get_igdb_website_by_id,
	__path_get_igdb_website_type_by_id, __path_get_igdb_website_types_by_ids,
	__path_get_igdb_websites_by_ids, __path_search_igdb_game_by_name,
};
use crate::routes::launchbox::{
	__path_get_lb_game_alternate_names, __path_get_lb_game_by_id, __path_get_lb_game_images,
	__path_list_lb_platforms, __path_search_lb_games,
};
use crate::routes::r#match::{
	__path_manually_match_company, __path_manually_match_game, __path_manually_match_platform,
};
use crate::routes::mobygames::{
	__path_get_mg_game_by_id, __path_get_mg_game_covers, __path_get_mg_game_screenshots,
	__path_list_mg_genres, __path_list_mg_platforms, __path_search_mg_games,
};
use crate::routes::openvgdb::{__path_get_ovgdb_release_by_id, __path_get_ovgdb_rom_by_hash};
use crate::routes::platform::{__path_get_all_platforms, __path_get_platform_by_id};
use crate::routes::screenscraper::{
	__path_get_ss_game_by_id, __path_get_ss_game_by_rom_name, __path_list_ss_systems,
	__path_search_ss_games,
};
use crate::routes::sgdb::{
	__path_get_sgdb_game_by_id, __path_get_sgdb_game_by_platform, __path_get_sgdb_grids_by_game,
	__path_get_sgdb_grids_by_platform, __path_get_sgdb_heroes_by_game,
	__path_get_sgdb_heroes_by_platform, __path_get_sgdb_icons_by_game,
	__path_get_sgdb_icons_by_platform, __path_get_sgdb_logos_by_game,
	__path_get_sgdb_logos_by_platform, __path_search_sgdb_games,
};
use crate::routes::suggestion::{
	__path_approve_suggestion, __path_create_company_suggestion, __path_create_game_suggestion,
	__path_create_platform_suggestion, __path_delete_suggestion, __path_get_all_suggestions,
	__path_get_suggestion_by_id, __path_submit_external_game_suggestion,
};
use crate::routes::user::{
	__path_create_or_get_by_discord_id, __path_get_user, __path_get_user_by_discord_id,
	__path_update_user_permission_level,
};
use service::model::external_suggestion::{
	ExternalGameMatchSuggestionPayload, ExternalProviderMapping,
};
use service::model::matching::{CompanyOrPlatformMatchRequest, GameMatchRequest};
use service::model::suggestion::{
	CompanyOrPlatformSuggestionRequest, GameSuggestionRequest, Suggestion,
	UpdatedMetadataMatchesFromSuggestionResponse,
};
use service::model::user::{
	CreateOrGetUserRequest, UpdateUserPermissionsRequest, User, UserPermissions,
};
use service::model::{
	AutomaticMatchReason, CompanyMetadataResponse, ExternalMetadata, FailedMatchReason,
	GameAndRelationMatchResult, GameAndRelationsResult, GameMatchType, GameMetadataMatchResult,
	ManualMatchMode, MetadataMatchType, MetadataProvider, PlatformMetadataResponse,
	PlaymatchCompany, PlaymatchDatFile, PlaymatchDatFileImport, PlaymatchGame, PlaymatchGameFile,
	PlaymatchPlatform, PlaymatchSignatureGroup, UpdatedMatchResult,
};
use service::providers::igdb::model::{
	AgeRating, AgeRatingCategory, AgeRatingContentDescriptionType, AgeRatingContentDescriptionV2,
	AgeRatingOrganization, AlternativeName, Artwork, ArtworkType, Character, CharacterGender,
	CharacterMugShot, CharacterSpecies, Collection, CollectionMembership, CollectionMembershipType,
	CollectionRelation, CollectionRelationType, CollectionType, Company, CompanyLogo, CompanySize,
	CompanyStatus, CompanyType, CompanyTypeHistory, CompanyWebsite, Cover, DateFormat, EntityType,
	Event, EventLogo, EventNetwork, ExternalGame, ExternalGameSource, Franchise, Game, GameEngine,
	GameEngineLogo, GameLocalization, GameMode, GameReleaseFormat, GameStatus, GameTimeToBeat,
	GameType, GameVersion, GameVersionFeature, GameVersionFeatureCategory, GameVersionFeatureValue,
	GameVersionFeatureValueEnum, GameVideo, Genre, InvolvedCompany, Keyword, Language,
	LanguageSupport, LanguageSupportType, MultiplayerMode, NetworkType, Platform, PlatformFamily,
	PlatformLogo, PlatformType, PlatformVersion, PlatformVersionCompany,
	PlatformVersionReleaseDate, PlatformWebsite, PlayerPerspective, PopularityPrimitive,
	PopularityType, Region, ReleaseDate, ReleaseDateRegion, ReleaseDateStatus, Report, ReportType,
	Screenshot, Theme, Website, WebsiteType,
};
use service::providers::launchbox::model::{LbGame, LbGameAlternateName, LbGameImage, LbPlatform};
use service::providers::mobygames::model::{
	MgAltTitle, MgCover, MgCoverGroup, MgCoversResp, MgGame, MgGamePlatformBrief, MgGenre,
	MgPlatform, MgSampleCover, MgSampleScreenshot, MgScreenshot, MgScreenshotsResp,
};
use service::providers::openvgdb::model::{OvgdbRelease, OvgdbRom, OvgdbRomMatch};
use service::providers::screenscraper::model::{
	SsEntityRef, SsGame, SsLocalizedName, SsRom, SsSystem, SsSystemNames,
};
use service::providers::steamgriddb::model::{
	AssetFilters, SgdbAsset, SgdbAssetMime, SgdbAssetType, SgdbAuthor, SgdbContentTag, SgdbGame,
	SgdbGridDimension, SgdbGridStyle, SgdbHeroDimension, SgdbHeroStyle, SgdbIconStyle,
	SgdbLogoStyle, SgdbPlatform, SgdbTriState,
};
use utoipa::OpenApi;
use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::openapi::{Components, ComponentsBuilder};

#[derive(OpenApi)]
#[openapi(
	info(
		title = "playmatch",
		description = "A blazingly fast microservice for matching ROM file hashes and caching game metadata. Originally designed for RetroRealm.",
		license(
			name = "MIT",
			url = "https://github.com/RetroRealm/playmatch/blob/develop/LICENSE.md"
		),
		contact(
			name = "DevYukine",
			email = "devyukine@gmx.de",
			url = "https://github.com/RetroRealm/playmatch"
		),
	),
	paths(
		health,
		ready,
		identify_game_with_metadata_ids,
		identify_game_and_relations,
		manually_match_game,
		manually_match_company,
		manually_match_platform,
		get_playmatch_game_by_id,
		get_playmatch_game_with_relations_by_id,
		get_suggestion_by_id,
		get_all_suggestions,
		create_game_suggestion,
		create_company_suggestion,
		create_platform_suggestion,
		approve_suggestion,
		delete_suggestion,
		submit_external_game_suggestion,
		create_or_get_by_discord_id,
		get_user_by_discord_id,
		get_user,
		update_user_permission_level,
		get_igdb_game_by_id,
		get_igdb_games_by_ids,
		search_igdb_game_by_name,
		get_igdb_age_rating_by_id,
		get_igdb_age_ratings_by_ids,
		get_igdb_alternative_name_by_id,
		get_igdb_alternative_names_by_ids,
		get_igdb_artwork_by_id,
		get_igdb_artworks_by_ids,
		get_igdb_collection_by_id,
		get_igdb_collections_by_ids,
		get_igdb_cover_by_id,
		get_igdb_covers_by_ids,
		get_igdb_external_game_by_id,
		get_igdb_external_games_by_ids,
		get_igdb_franchise_by_id,
		get_igdb_franchises_by_ids,
		get_igdb_genre_by_id,
		get_igdb_genres_by_ids,
		get_igdb_age_rating_category_by_id,
		get_igdb_age_rating_categories_by_ids,
		get_igdb_age_rating_content_description_v2_by_id,
		get_igdb_age_rating_content_descriptions_v2_by_ids,
		get_igdb_age_rating_content_description_type_by_id,
		get_igdb_age_rating_content_description_types_by_ids,
		get_igdb_age_rating_organization_by_id,
		get_igdb_age_rating_organizations_by_ids,
		get_igdb_company_status_by_id,
		get_igdb_company_statuses_by_ids,
		get_igdb_date_format_by_id,
		get_igdb_date_formats_by_ids,
		get_igdb_external_game_source_by_id,
		get_igdb_external_game_sources_by_ids,
		get_igdb_game_release_format_by_id,
		get_igdb_game_release_formats_by_ids,
		get_igdb_game_status_by_id,
		get_igdb_game_statuses_by_ids,
		get_igdb_game_type_by_id,
		get_igdb_game_types_by_ids,
		get_igdb_platform_type_by_id,
		get_igdb_platform_types_by_ids,
		get_igdb_release_date_region_by_id,
		get_igdb_release_date_regions_by_ids,
		get_igdb_website_type_by_id,
		get_igdb_website_types_by_ids,
		get_igdb_artwork_type_by_id,
		get_igdb_artwork_types_by_ids,
		get_igdb_character_mug_shot_by_id,
		get_igdb_character_mug_shots_by_ids,
		get_igdb_company_size_by_id,
		get_igdb_company_sizes_by_ids,
		get_igdb_company_type_by_id,
		get_igdb_company_types_by_ids,
		get_igdb_company_type_history_by_id,
		get_igdb_company_type_histories_by_ids,
		get_igdb_entity_type_by_id,
		get_igdb_entity_types_by_ids,
		get_igdb_game_time_to_beat_by_id,
		get_igdb_game_time_to_beats_by_ids,
		get_igdb_report_by_id,
		get_igdb_reports_by_ids,
		get_igdb_report_type_by_id,
		get_igdb_report_types_by_ids,
		get_igdb_character_by_id,
		get_igdb_characters_by_ids,
		get_igdb_character_gender_by_id,
		get_igdb_character_genders_by_ids,
		get_igdb_character_species_by_id,
		get_igdb_character_species_by_ids,
		get_igdb_collection_membership_by_id,
		get_igdb_collection_memberships_by_ids,
		get_igdb_collection_membership_type_by_id,
		get_igdb_collection_membership_types_by_ids,
		get_igdb_collection_relation_by_id,
		get_igdb_collection_relations_by_ids,
		get_igdb_collection_relation_type_by_id,
		get_igdb_collection_relation_types_by_ids,
		get_igdb_collection_type_by_id,
		get_igdb_collection_types_by_ids,
		get_igdb_company_by_id,
		get_igdb_companies_by_ids,
		get_igdb_company_logo_by_id,
		get_igdb_company_logos_by_ids,
		get_igdb_company_website_by_id,
		get_igdb_company_websites_by_ids,
		get_igdb_event_by_id,
		get_igdb_events_by_ids,
		get_igdb_event_logo_by_id,
		get_igdb_event_logos_by_ids,
		get_igdb_event_network_by_id,
		get_igdb_event_networks_by_ids,
		get_igdb_game_engine_by_id,
		get_igdb_game_engines_by_ids,
		get_igdb_game_engine_logo_by_id,
		get_igdb_game_engine_logos_by_ids,
		get_igdb_game_localization_by_id,
		get_igdb_game_localizations_by_ids,
		get_igdb_game_mode_by_id,
		get_igdb_game_modes_by_ids,
		get_igdb_game_version_by_id,
		get_igdb_game_versions_by_ids,
		get_igdb_game_version_feature_by_id,
		get_igdb_game_version_features_by_ids,
		get_igdb_game_version_feature_value_by_id,
		get_igdb_game_version_feature_values_by_ids,
		get_igdb_game_video_by_id,
		get_igdb_game_videos_by_ids,
		get_igdb_involved_company_by_id,
		get_igdb_involved_companies_by_ids,
		get_igdb_keyword_by_id,
		get_igdb_keywords_by_ids,
		get_igdb_language_by_id,
		get_igdb_languages_by_ids,
		get_igdb_language_support_by_id,
		get_igdb_language_supports_by_ids,
		get_igdb_language_support_type_by_id,
		get_igdb_language_support_types_by_ids,
		get_igdb_multiplayer_mode_by_id,
		get_igdb_multiplayer_modes_by_ids,
		get_igdb_network_type_by_id,
		get_igdb_network_types_by_ids,
		get_igdb_platform_by_id,
		get_igdb_platforms_by_ids,
		get_igdb_platform_family_by_id,
		get_igdb_platform_families_by_ids,
		get_igdb_platform_logo_by_id,
		get_igdb_platform_logos_by_ids,
		get_igdb_platform_version_by_id,
		get_igdb_platform_versions_by_ids,
		get_igdb_platform_version_company_by_id,
		get_igdb_platform_version_companies_by_ids,
		get_igdb_platform_version_release_date_by_id,
		get_igdb_platform_version_release_dates_by_ids,
		get_igdb_platform_website_by_id,
		get_igdb_platform_websites_by_ids,
		get_igdb_player_perspective_by_id,
		get_igdb_player_perspectives_by_ids,
		get_igdb_popularity_primitive_by_id,
		get_igdb_popularity_primitives_by_ids,
		get_igdb_popularity_type_by_id,
		get_igdb_popularity_types_by_ids,
		get_igdb_region_by_id,
		get_igdb_regions_by_ids,
		get_igdb_release_date_by_id,
		get_igdb_release_dates_by_ids,
		get_igdb_release_date_status_by_id,
		get_igdb_release_date_statuses_by_ids,
		get_igdb_screenshot_by_id,
		get_igdb_screenshots_by_ids,
		get_igdb_theme_by_id,
		get_igdb_themes_by_ids,
		get_igdb_website_by_id,
		get_igdb_websites_by_ids,
		get_all_companies,
		get_company_by_id,
		get_all_platforms,
		get_platform_by_id,
		get_sgdb_game_by_id,
		get_sgdb_game_by_platform,
		search_sgdb_games,
		get_sgdb_grids_by_game,
		get_sgdb_grids_by_platform,
		get_sgdb_heroes_by_game,
		get_sgdb_heroes_by_platform,
		get_sgdb_logos_by_game,
		get_sgdb_logos_by_platform,
		get_sgdb_icons_by_game,
		get_sgdb_icons_by_platform,
		list_ss_systems,
		get_ss_game_by_id,
		search_ss_games,
		get_ss_game_by_rom_name,
		list_mg_platforms,
		list_mg_genres,
		get_mg_game_by_id,
		search_mg_games,
		get_mg_game_covers,
		get_mg_game_screenshots,
		list_lb_platforms,
		get_lb_game_by_id,
		search_lb_games,
		get_lb_game_alternate_names,
		get_lb_game_images,
		get_ovgdb_release_by_id,
		get_ovgdb_rom_by_hash
	),
	components(schemas(
		GameMetadataMatchResult,
		CompanyMetadataResponse,
		PlatformMetadataResponse,
		GameMatchType,
		ExternalMetadata,
		MetadataMatchType,
		ManualMatchMode,
		FailedMatchReason,
		MetadataProvider,
		AutomaticMatchReason,
		AgeRating,
		AgeRatingCategory,
		AgeRatingContentDescriptionType,
		AgeRatingContentDescriptionV2,
		AgeRatingOrganization,
		AlternativeName,
		Artwork,
		ArtworkType,
		Character,
		CharacterGender,
		CharacterMugShot,
		CharacterSpecies,
		Collection,
		CollectionMembership,
		CollectionMembershipType,
		CollectionRelation,
		CollectionRelationType,
		CollectionType,
		Company,
		CompanyLogo,
		CompanySize,
		CompanyStatus,
		CompanyType,
		CompanyTypeHistory,
		CompanyWebsite,
		Cover,
		DateFormat,
		EntityType,
		Event,
		EventLogo,
		EventNetwork,
		ExternalGame,
		ExternalGameSource,
		Franchise,
		Game,
		GameEngine,
		GameEngineLogo,
		GameLocalization,
		GameMode,
		GameReleaseFormat,
		GameStatus,
		GameTimeToBeat,
		GameType,
		GameVersion,
		GameVersionFeature,
		GameVersionFeatureCategory,
		GameVersionFeatureValue,
		GameVersionFeatureValueEnum,
		GameVideo,
		Genre,
		InvolvedCompany,
		Keyword,
		Language,
		LanguageSupport,
		LanguageSupportType,
		MultiplayerMode,
		GameMatchRequest,
		CompanyOrPlatformMatchRequest,
		GameAndRelationMatchResult,
		GameAndRelationsResult,
		PlaymatchCompany,
		PlaymatchGame,
		PlaymatchGameFile,
		PlaymatchPlatform,
		PlaymatchDatFile,
		PlaymatchDatFileImport,
		PlaymatchSignatureGroup,
		GameSuggestionRequest,
		CompanyOrPlatformSuggestionRequest,
		ExternalGameMatchSuggestionPayload,
		ExternalProviderMapping,
		UpdatedMetadataMatchesFromSuggestionResponse,
		Suggestion,
		User,
		UserPermissions,
		CreateOrGetUserRequest,
		UpdateUserPermissionsRequest,
		NetworkType,
		Platform,
		PlatformFamily,
		PlatformLogo,
		PlatformType,
		PlatformVersion,
		PlatformVersionCompany,
		PlatformVersionReleaseDate,
		PlatformWebsite,
		PlayerPerspective,
		PopularityPrimitive,
		PopularityType,
		Region,
		ReleaseDate,
		ReleaseDateRegion,
		ReleaseDateStatus,
		Report,
		ReportType,
		Screenshot,
		Theme,
		UpdatedMatchResult,
		Website,
		WebsiteType,
		SgdbGame,
		SgdbAsset,
		SgdbAuthor,
		SgdbPlatform,
		SgdbGridStyle,
		SgdbHeroStyle,
		SgdbLogoStyle,
		SgdbIconStyle,
		SgdbGridDimension,
		SgdbHeroDimension,
		SgdbAssetMime,
		SgdbAssetType,
		SgdbContentTag,
		SgdbTriState,
		AssetFilters,
		SsGame,
		SsLocalizedName,
		SsRom,
		SsSystem,
		SsSystemNames,
		SsEntityRef,
		MgGame,
		MgAltTitle,
		MgGamePlatformBrief,
		MgSampleCover,
		MgSampleScreenshot,
		MgPlatform,
		MgGenre,
		MgCover,
		MgCoverGroup,
		MgCoversResp,
		MgScreenshot,
		MgScreenshotsResp,
		LbGame,
		LbGameAlternateName,
		LbGameImage,
		LbPlatform,
		OvgdbRelease,
		OvgdbRom,
		OvgdbRomMatch
	))
)]
pub struct ApiDoc;

pub fn create_openapi() -> utoipa::openapi::OpenApi {
	let mut openapi = ApiDoc::openapi();

	let existing_components = openapi
		.components
		.take()
		.unwrap_or_else(Components::default);

	let new_components = ComponentsBuilder::from(existing_components)
		.security_scheme(
			"bearer_auth",
			SecurityScheme::Http(
				HttpBuilder::new()
					.scheme(HttpAuthScheme::Bearer)
					.bearer_format("JWT")
					.build(),
			),
		)
		.build();

	openapi.components = Some(new_components);

	openapi
}
