//! OpenAPI document for the v2 surface, the primary document. The per-document
//! server URL supplies the `/api/v2` prefix; handlers carry relative paths.

use crate::model::bulk::doc::{
	BulkCompaniesByIdResponse, BulkCompaniesByIdResult, BulkDatFilesByIdResponse,
	BulkDatFilesByIdResult, BulkGameFilesByIdResponse, BulkGameFilesByIdResult,
	BulkGamesByIdResponse, BulkGamesByIdResult, BulkIdentifyIdsResponse, BulkIdentifyIdsResult,
	BulkIdentifyRelationsResponse, BulkIdentifyRelationsResult, BulkPlatformsByIdResponse,
	BulkPlatformsByIdResult, BulkSignatureGroupsByIdResponse, BulkSignatureGroupsByIdResult,
};
use crate::model::bulk::{
	BulkByIdStatusV2, BulkByIdSummary, BulkCache, BulkIdentifyItem, BulkIdentifyRequest,
	BulkIdentifySummary, BulkIdsRequest, BulkItemError, BulkItemStatus,
};
use crate::model::dat_file::ReverseLookupLevel;
use crate::model::game::CloneDirectionParam;
use crate::model::pagination::{
	PageMeta, PageOfCompanyMetadataResponse, PageOfDatFileGame, PageOfDatFileImportTimelineEntry,
	PageOfDatFileSummary, PageOfGameMetadataResponse, PageOfGameNameSearchResult,
	PageOfPlatformMetadataResponse, PageOfPlaymatchGameFile, PageOfPlaymatchSignatureGroup,
	PageOfSuggestion,
};
use crate::model::sgdb::SgdbAssetFilterQuery;
use crate::routes::health::{__path_health, __path_ready};
use crate::routes::igdb::{
	__path_get_igdb_age_rating_by_id, __path_get_igdb_age_rating_categories_by_ids,
	__path_get_igdb_age_rating_category_by_id,
	__path_get_igdb_age_rating_content_description_type_by_id,
	__path_get_igdb_age_rating_content_description_types_by_ids,
	__path_get_igdb_age_rating_content_description_v2_by_id,
	__path_get_igdb_age_rating_content_descriptions_v2_by_ids,
	__path_get_igdb_age_rating_organization_by_id, __path_get_igdb_age_rating_organizations_by_ids,
	__path_get_igdb_age_ratings_by_ids, __path_get_igdb_alternative_name_by_id,
	__path_get_igdb_alternative_names_by_ids, __path_get_igdb_artwork_by_id,
	__path_get_igdb_artwork_type_by_id, __path_get_igdb_artwork_types_by_ids,
	__path_get_igdb_artworks_by_ids, __path_get_igdb_character_by_id,
	__path_get_igdb_character_gender_by_id, __path_get_igdb_character_genders_by_ids,
	__path_get_igdb_character_mug_shot_by_id, __path_get_igdb_character_mug_shots_by_ids,
	__path_get_igdb_character_species_by_id, __path_get_igdb_character_species_by_ids,
	__path_get_igdb_characters_by_ids, __path_get_igdb_collection_by_id,
	__path_get_igdb_collection_membership_by_id, __path_get_igdb_collection_membership_type_by_id,
	__path_get_igdb_collection_membership_types_by_ids,
	__path_get_igdb_collection_memberships_by_ids, __path_get_igdb_collection_relation_by_id,
	__path_get_igdb_collection_relation_type_by_id,
	__path_get_igdb_collection_relation_types_by_ids, __path_get_igdb_collection_relations_by_ids,
	__path_get_igdb_collection_type_by_id, __path_get_igdb_collection_types_by_ids,
	__path_get_igdb_collections_by_ids, __path_get_igdb_companies_by_ids,
	__path_get_igdb_company_by_id, __path_get_igdb_company_logo_by_id,
	__path_get_igdb_company_logos_by_ids, __path_get_igdb_company_size_by_id,
	__path_get_igdb_company_sizes_by_ids, __path_get_igdb_company_status_by_id,
	__path_get_igdb_company_statuses_by_ids, __path_get_igdb_company_type_by_id,
	__path_get_igdb_company_type_histories_by_ids, __path_get_igdb_company_type_history_by_id,
	__path_get_igdb_company_types_by_ids, __path_get_igdb_company_website_by_id,
	__path_get_igdb_company_websites_by_ids, __path_get_igdb_cover_by_id,
	__path_get_igdb_covers_by_ids, __path_get_igdb_date_format_by_id,
	__path_get_igdb_date_formats_by_ids, __path_get_igdb_entity_type_by_id,
	__path_get_igdb_entity_types_by_ids, __path_get_igdb_event_by_id,
	__path_get_igdb_event_logo_by_id, __path_get_igdb_event_logos_by_ids,
	__path_get_igdb_event_network_by_id, __path_get_igdb_event_networks_by_ids,
	__path_get_igdb_events_by_ids, __path_get_igdb_external_game_by_id,
	__path_get_igdb_external_game_source_by_id, __path_get_igdb_external_game_sources_by_ids,
	__path_get_igdb_external_games_by_ids, __path_get_igdb_franchise_by_id,
	__path_get_igdb_franchises_by_ids, __path_get_igdb_game_by_id,
	__path_get_igdb_game_engine_by_id, __path_get_igdb_game_engine_logo_by_id,
	__path_get_igdb_game_engine_logos_by_ids, __path_get_igdb_game_engines_by_ids,
	__path_get_igdb_game_localization_by_id, __path_get_igdb_game_localizations_by_ids,
	__path_get_igdb_game_mode_by_id, __path_get_igdb_game_modes_by_ids,
	__path_get_igdb_game_release_format_by_id, __path_get_igdb_game_release_formats_by_ids,
	__path_get_igdb_game_status_by_id, __path_get_igdb_game_statuses_by_ids,
	__path_get_igdb_game_time_to_beat_by_id, __path_get_igdb_game_time_to_beats_by_ids,
	__path_get_igdb_game_type_by_id, __path_get_igdb_game_types_by_ids,
	__path_get_igdb_game_version_by_id, __path_get_igdb_game_version_feature_by_id,
	__path_get_igdb_game_version_feature_value_by_id,
	__path_get_igdb_game_version_feature_values_by_ids,
	__path_get_igdb_game_version_features_by_ids, __path_get_igdb_game_versions_by_ids,
	__path_get_igdb_game_video_by_id, __path_get_igdb_game_videos_by_ids,
	__path_get_igdb_games_by_ids, __path_get_igdb_genre_by_id, __path_get_igdb_genres_by_ids,
	__path_get_igdb_involved_companies_by_ids, __path_get_igdb_involved_company_by_id,
	__path_get_igdb_keyword_by_id, __path_get_igdb_keywords_by_ids, __path_get_igdb_language_by_id,
	__path_get_igdb_language_support_by_id, __path_get_igdb_language_support_type_by_id,
	__path_get_igdb_language_support_types_by_ids, __path_get_igdb_language_supports_by_ids,
	__path_get_igdb_languages_by_ids, __path_get_igdb_multiplayer_mode_by_id,
	__path_get_igdb_multiplayer_modes_by_ids, __path_get_igdb_network_type_by_id,
	__path_get_igdb_network_types_by_ids, __path_get_igdb_platform_by_id,
	__path_get_igdb_platform_families_by_ids, __path_get_igdb_platform_family_by_id,
	__path_get_igdb_platform_logo_by_id, __path_get_igdb_platform_logos_by_ids,
	__path_get_igdb_platform_type_by_id, __path_get_igdb_platform_types_by_ids,
	__path_get_igdb_platform_version_by_id, __path_get_igdb_platform_version_companies_by_ids,
	__path_get_igdb_platform_version_company_by_id,
	__path_get_igdb_platform_version_release_date_by_id,
	__path_get_igdb_platform_version_release_dates_by_ids,
	__path_get_igdb_platform_versions_by_ids, __path_get_igdb_platform_website_by_id,
	__path_get_igdb_platform_websites_by_ids, __path_get_igdb_platforms_by_ids,
	__path_get_igdb_player_perspective_by_id, __path_get_igdb_player_perspectives_by_ids,
	__path_get_igdb_popularity_primitive_by_id, __path_get_igdb_popularity_primitives_by_ids,
	__path_get_igdb_popularity_type_by_id, __path_get_igdb_popularity_types_by_ids,
	__path_get_igdb_region_by_id, __path_get_igdb_regions_by_ids,
	__path_get_igdb_release_date_by_id, __path_get_igdb_release_date_region_by_id,
	__path_get_igdb_release_date_regions_by_ids, __path_get_igdb_release_date_status_by_id,
	__path_get_igdb_release_date_statuses_by_ids, __path_get_igdb_release_dates_by_ids,
	__path_get_igdb_report_by_id, __path_get_igdb_report_type_by_id,
	__path_get_igdb_report_types_by_ids, __path_get_igdb_reports_by_ids,
	__path_get_igdb_screenshot_by_id, __path_get_igdb_screenshots_by_ids,
	__path_get_igdb_theme_by_id, __path_get_igdb_themes_by_ids, __path_get_igdb_website_by_id,
	__path_get_igdb_website_type_by_id, __path_get_igdb_website_types_by_ids,
	__path_get_igdb_websites_by_ids, __path_search_igdb_game_by_name,
};
use crate::routes::launchbox::{
	__path_get_lb_game_alternate_names, __path_get_lb_game_by_id, __path_get_lb_game_images,
	__path_list_lb_platforms, __path_search_lb_games,
};
use crate::routes::r#match::{
	__path_manually_match_company, __path_manually_match_game, __path_manually_match_platform,
};
use crate::routes::mobygames::{
	__path_get_mg_game_by_id, __path_get_mg_game_covers, __path_get_mg_game_screenshots,
	__path_list_mg_genres, __path_list_mg_platforms, __path_search_mg_games,
};
use crate::routes::openvgdb::{__path_get_ovgdb_release_by_id, __path_get_ovgdb_rom_by_hash};
use crate::routes::retroachievements::{
	__path_get_ra_game_by_hash, __path_get_ra_game_by_id, __path_list_ra_systems,
	__path_search_ra_games,
};
use crate::routes::screenscraper::{
	__path_get_ss_game_by_id, __path_get_ss_game_by_rom_name, __path_list_ss_systems,
	__path_search_ss_games,
};
use crate::routes::sgdb::{
	__path_get_sgdb_game_by_id, __path_get_sgdb_game_by_platform, __path_get_sgdb_grids_by_game,
	__path_get_sgdb_grids_by_platform, __path_get_sgdb_heroes_by_game,
	__path_get_sgdb_heroes_by_platform, __path_get_sgdb_icons_by_game,
	__path_get_sgdb_icons_by_platform, __path_get_sgdb_logos_by_game,
	__path_get_sgdb_logos_by_platform, __path_search_sgdb_games,
};
use crate::routes::suggestion::{
	__path_approve_suggestion, __path_create_company_suggestion, __path_create_game_suggestion,
	__path_create_platform_suggestion, __path_delete_suggestion, __path_get_suggestion_by_id,
	__path_submit_external_game_suggestion,
};
use crate::routes::user::__path_get_user;
use crate::routes::v2::bulk_by_id::{
	__path_bulk_companies_by_id_v2, __path_bulk_dat_files_by_id_v2,
	__path_bulk_game_files_by_id_v2, __path_bulk_games_by_id_v2, __path_bulk_platforms_by_id_v2,
	__path_bulk_signature_groups_by_id_v2,
};
use crate::routes::v2::company::{
	__path_get_company_by_id_v2, __path_list_companies_v2, __path_search_companies_v2,
};
use crate::routes::v2::dat_file::{
	__path_get_dat_file_by_id_v2, __path_get_dat_file_import_v2, __path_list_dat_file_games_v2,
	__path_list_dat_file_imports_v2, __path_list_dat_files_by_hash_v2, __path_list_dat_files_v2,
	__path_list_game_dat_files_v2,
};
use crate::routes::v2::error::V2ErrorBody;
use crate::routes::v2::game::{
	__path_get_game_by_id_v2, __path_get_game_file_by_id_v2, __path_get_game_file_history_by_id_v2,
	__path_get_game_file_presence_v2, __path_get_game_with_relations_by_id_v2,
	__path_get_games_by_name_v2, __path_list_game_clones_v2, __path_list_game_files_v2,
	__path_list_game_mappings_v2, __path_list_games_v2, __path_search_games_v2,
};
use crate::routes::v2::identify::{
	__path_identify_game_and_relations_v2, __path_identify_game_with_metadata_ids_v2,
};
use crate::routes::v2::identify_bulk::{
	__path_identify_bulk_ids_v2, __path_identify_bulk_relations_v2,
};
use crate::routes::v2::platform::{
	__path_get_platform_by_id_v2, __path_list_platforms_v2, __path_search_platforms_v2,
};
use crate::routes::v2::signature_group::{
	__path_get_signature_group_by_id_v2, __path_list_signature_group_dat_files_v2,
	__path_list_signature_group_games_v2, __path_list_signature_groups_v2,
	__path_search_signature_groups_v2,
};
use crate::routes::v2::stats::{__path_get_platform_stats_v2, __path_get_stats_v2};
use crate::routes::v2::suggestion::__path_list_suggestions_v2;
use crate::routes::v2::user::{
	__path_create_or_get_by_discord_id_v2, __path_get_user_by_discord_id_v2,
	__path_update_user_permission_level_v2,
};
use service::entities::dat_file::{
	DatFileDetail, DatFileGame, DatFileImportRef, DatFileImportTimelineEntry, DatFilePresence,
	DatFileSummary, LatestDatFileImport, NamedRef, PresenceResult, SignatureGroupPresence,
};
use service::entities::game::{
	CloneGraph, CloneGraphNode, GameFilePresenceEntry, GameProviderMapping,
};
use service::entities::stats::{PlatformStats, ServiceStats};
use service::model::external_suggestion::{
	ExternalGameMatchSuggestionPayload, ExternalProviderMapping,
};
use service::model::matching::{CompanyOrPlatformMatchRequest, GameMatchRequest};
use service::model::suggestion::{
	CompanyOrPlatformSuggestionRequest, GameSuggestionRequest, Suggestion,
	UpdatedMetadataMatchesFromSuggestionResponse,
};
use service::model::user::{
	CreateOrGetUserRequestV2, UpdateUserPermissionsRequestV2, User, UserPermissions,
};
use service::model::{
	AutomaticMatchReason, AutomaticMatchReasonV2, CompanyMetadataResponse, ExternalMetadata,
	ExternalMetadataV2, FailedMatchReason, GameAndRelationMatchResultV2, GameAndRelationsResultV2,
	GameFileMatchSearch, GameMatchType, GameMetadataMatchResult, GameMetadataResponse,
	GameNameSearchResultV2, ManualMatchMode, MetadataMatchType, MetadataProvider,
	PlatformMetadataResponse, PlaymatchCompanyV2, PlaymatchDatFileImportV2, PlaymatchDatFileV2,
	PlaymatchGameFileV2, PlaymatchGameV2, PlaymatchPlatformV2, PlaymatchSignatureGroupV2,
	UpdatedMatchResult,
};
use service::providers::igdb::model::{
	AgeRating, AgeRatingCategory, AgeRatingContentDescriptionType, AgeRatingContentDescriptionV2,
	AgeRatingOrganization, AlternativeName, Artwork, ArtworkType, Character, CharacterGender,
	CharacterMugShot, CharacterSpecies, Collection, CollectionMembership, CollectionMembershipType,
	CollectionRelation, CollectionRelationType, CollectionType, Company, CompanyLogo, CompanySize,
	CompanyStatus, CompanyType, CompanyTypeHistory, CompanyWebsite, Cover, DateFormat, EntityType,
	Event, EventLogo, EventNetwork, ExternalGame, ExternalGameSource, Franchise, Game, GameEngine,
	GameEngineLogo, GameLocalization, GameMode, GameReleaseFormat, GameStatus, GameTimeToBeat,
	GameType, GameVersion, GameVersionFeature, GameVersionFeatureCategory, GameVersionFeatureValue,
	GameVersionFeatureValueEnum, GameVideo, Genre, InvolvedCompany, Keyword, Language,
	LanguageSupport, LanguageSupportType, MultiplayerMode, NetworkType, Platform, PlatformFamily,
	PlatformLogo, PlatformType, PlatformVersion, PlatformVersionCompany,
	PlatformVersionReleaseDate, PlatformWebsite, PlayerPerspective, PopularityPrimitive,
	PopularityType, Region, ReleaseDate, ReleaseDateRegion, ReleaseDateStatus, Report, ReportType,
	Screenshot, Theme, Website, WebsiteType,
};
use service::providers::launchbox::model::{LbGame, LbGameAlternateName, LbGameImage, LbPlatform};
use service::providers::mobygames::model::{
	MgAltTitle, MgCover, MgCoverGroup, MgCoversResp, MgGame, MgGamePlatformBrief, MgGenre,
	MgPlatform, MgSampleCover, MgSampleScreenshot, MgScreenshot, MgScreenshotsResp,
};
use service::providers::openvgdb::model::{OvgdbRelease, OvgdbRom, OvgdbRomMatch};
use service::providers::retroachievements::model::{RaGame, RaGameHash, RaGameMatch, RaSystem};
use service::providers::screenscraper::model::{
	SsEntityRef, SsGame, SsLocalizedName, SsRom, SsSystem, SsSystemNames,
};
use service::providers::steamgriddb::model::{
	AssetFilters, SgdbAsset, SgdbAssetMime, SgdbAssetType, SgdbAuthor, SgdbContentTag, SgdbGame,
	SgdbGridDimension, SgdbGridStyle, SgdbHeroDimension, SgdbHeroStyle, SgdbIconStyle,
	SgdbLogoStyle, SgdbPlatform, SgdbTriState,
};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
	info(
		title = "playmatch",
		license(
			name = "MIT",
			url = "https://github.com/RetroRealm/playmatch/blob/develop/LICENSE.md"
		),
		contact(
			name = "DevYukine",
			email = "devyukine@gmx.de",
			url = "https://github.com/RetroRealm/playmatch"
		),
	),
	servers(
		(url = "/api/v2", description = "Version 2")
	),
	paths(
		get_stats_v2,
		get_platform_stats_v2,
		list_companies_v2,
		get_company_by_id_v2,
		list_platforms_v2,
		get_platform_by_id_v2,
		list_signature_groups_v2,
		list_signature_group_dat_files_v2,
		list_signature_group_games_v2,
		get_signature_group_by_id_v2,
		list_games_v2,
		search_games_v2,
		get_game_by_id_v2,
		get_game_with_relations_by_id_v2,
		get_games_by_name_v2,
		get_game_file_presence_v2,
		get_game_file_by_id_v2,
		list_game_files_v2,
		list_game_mappings_v2,
		list_game_clones_v2,
		list_dat_files_v2,
		list_dat_files_by_hash_v2,
		get_dat_file_by_id_v2,
		list_dat_file_games_v2,
		list_dat_file_imports_v2,
		get_dat_file_import_v2,
		list_game_dat_files_v2,
		identify_bulk_ids_v2,
		identify_bulk_relations_v2,
		bulk_games_by_id_v2,
		bulk_platforms_by_id_v2,
		bulk_companies_by_id_v2,
		bulk_signature_groups_by_id_v2,
		bulk_dat_files_by_id_v2,
		bulk_game_files_by_id_v2,
		search_companies_v2,
		search_platforms_v2,
		search_signature_groups_v2,
		list_suggestions_v2,
		health,
		ready,
		identify_game_with_metadata_ids_v2,
		identify_game_and_relations_v2,
		manually_match_game,
		manually_match_company,
		manually_match_platform,
		get_game_file_history_by_id_v2,
		get_suggestion_by_id,
		create_game_suggestion,
		create_company_suggestion,
		create_platform_suggestion,
		approve_suggestion,
		delete_suggestion,
		submit_external_game_suggestion,
		create_or_get_by_discord_id_v2,
		get_user_by_discord_id_v2,
		get_user,
		update_user_permission_level_v2,
		get_igdb_game_by_id,
		get_igdb_games_by_ids,
		search_igdb_game_by_name,
		get_igdb_age_rating_by_id,
		get_igdb_age_ratings_by_ids,
		get_igdb_alternative_name_by_id,
		get_igdb_alternative_names_by_ids,
		get_igdb_artwork_by_id,
		get_igdb_artworks_by_ids,
		get_igdb_collection_by_id,
		get_igdb_collections_by_ids,
		get_igdb_cover_by_id,
		get_igdb_covers_by_ids,
		get_igdb_external_game_by_id,
		get_igdb_external_games_by_ids,
		get_igdb_franchise_by_id,
		get_igdb_franchises_by_ids,
		get_igdb_genre_by_id,
		get_igdb_genres_by_ids,
		get_igdb_age_rating_category_by_id,
		get_igdb_age_rating_categories_by_ids,
		get_igdb_age_rating_content_description_v2_by_id,
		get_igdb_age_rating_content_descriptions_v2_by_ids,
		get_igdb_age_rating_content_description_type_by_id,
		get_igdb_age_rating_content_description_types_by_ids,
		get_igdb_age_rating_organization_by_id,
		get_igdb_age_rating_organizations_by_ids,
		get_igdb_company_status_by_id,
		get_igdb_company_statuses_by_ids,
		get_igdb_date_format_by_id,
		get_igdb_date_formats_by_ids,
		get_igdb_external_game_source_by_id,
		get_igdb_external_game_sources_by_ids,
		get_igdb_game_release_format_by_id,
		get_igdb_game_release_formats_by_ids,
		get_igdb_game_status_by_id,
		get_igdb_game_statuses_by_ids,
		get_igdb_game_type_by_id,
		get_igdb_game_types_by_ids,
		get_igdb_platform_type_by_id,
		get_igdb_platform_types_by_ids,
		get_igdb_release_date_region_by_id,
		get_igdb_release_date_regions_by_ids,
		get_igdb_website_type_by_id,
		get_igdb_website_types_by_ids,
		get_igdb_artwork_type_by_id,
		get_igdb_artwork_types_by_ids,
		get_igdb_character_mug_shot_by_id,
		get_igdb_character_mug_shots_by_ids,
		get_igdb_company_size_by_id,
		get_igdb_company_sizes_by_ids,
		get_igdb_company_type_by_id,
		get_igdb_company_types_by_ids,
		get_igdb_company_type_history_by_id,
		get_igdb_company_type_histories_by_ids,
		get_igdb_entity_type_by_id,
		get_igdb_entity_types_by_ids,
		get_igdb_game_time_to_beat_by_id,
		get_igdb_game_time_to_beats_by_ids,
		get_igdb_report_by_id,
		get_igdb_reports_by_ids,
		get_igdb_report_type_by_id,
		get_igdb_report_types_by_ids,
		get_igdb_character_by_id,
		get_igdb_characters_by_ids,
		get_igdb_character_gender_by_id,
		get_igdb_character_genders_by_ids,
		get_igdb_character_species_by_id,
		get_igdb_character_species_by_ids,
		get_igdb_collection_membership_by_id,
		get_igdb_collection_memberships_by_ids,
		get_igdb_collection_membership_type_by_id,
		get_igdb_collection_membership_types_by_ids,
		get_igdb_collection_relation_by_id,
		get_igdb_collection_relations_by_ids,
		get_igdb_collection_relation_type_by_id,
		get_igdb_collection_relation_types_by_ids,
		get_igdb_collection_type_by_id,
		get_igdb_collection_types_by_ids,
		get_igdb_company_by_id,
		get_igdb_companies_by_ids,
		get_igdb_company_logo_by_id,
		get_igdb_company_logos_by_ids,
		get_igdb_company_website_by_id,
		get_igdb_company_websites_by_ids,
		get_igdb_event_by_id,
		get_igdb_events_by_ids,
		get_igdb_event_logo_by_id,
		get_igdb_event_logos_by_ids,
		get_igdb_event_network_by_id,
		get_igdb_event_networks_by_ids,
		get_igdb_game_engine_by_id,
		get_igdb_game_engines_by_ids,
		get_igdb_game_engine_logo_by_id,
		get_igdb_game_engine_logos_by_ids,
		get_igdb_game_localization_by_id,
		get_igdb_game_localizations_by_ids,
		get_igdb_game_mode_by_id,
		get_igdb_game_modes_by_ids,
		get_igdb_game_version_by_id,
		get_igdb_game_versions_by_ids,
		get_igdb_game_version_feature_by_id,
		get_igdb_game_version_features_by_ids,
		get_igdb_game_version_feature_value_by_id,
		get_igdb_game_version_feature_values_by_ids,
		get_igdb_game_video_by_id,
		get_igdb_game_videos_by_ids,
		get_igdb_involved_company_by_id,
		get_igdb_involved_companies_by_ids,
		get_igdb_keyword_by_id,
		get_igdb_keywords_by_ids,
		get_igdb_language_by_id,
		get_igdb_languages_by_ids,
		get_igdb_language_support_by_id,
		get_igdb_language_supports_by_ids,
		get_igdb_language_support_type_by_id,
		get_igdb_language_support_types_by_ids,
		get_igdb_multiplayer_mode_by_id,
		get_igdb_multiplayer_modes_by_ids,
		get_igdb_network_type_by_id,
		get_igdb_network_types_by_ids,
		get_igdb_platform_by_id,
		get_igdb_platforms_by_ids,
		get_igdb_platform_family_by_id,
		get_igdb_platform_families_by_ids,
		get_igdb_platform_logo_by_id,
		get_igdb_platform_logos_by_ids,
		get_igdb_platform_version_by_id,
		get_igdb_platform_versions_by_ids,
		get_igdb_platform_version_company_by_id,
		get_igdb_platform_version_companies_by_ids,
		get_igdb_platform_version_release_date_by_id,
		get_igdb_platform_version_release_dates_by_ids,
		get_igdb_platform_website_by_id,
		get_igdb_platform_websites_by_ids,
		get_igdb_player_perspective_by_id,
		get_igdb_player_perspectives_by_ids,
		get_igdb_popularity_primitive_by_id,
		get_igdb_popularity_primitives_by_ids,
		get_igdb_popularity_type_by_id,
		get_igdb_popularity_types_by_ids,
		get_igdb_region_by_id,
		get_igdb_regions_by_ids,
		get_igdb_release_date_by_id,
		get_igdb_release_dates_by_ids,
		get_igdb_release_date_status_by_id,
		get_igdb_release_date_statuses_by_ids,
		get_igdb_screenshot_by_id,
		get_igdb_screenshots_by_ids,
		get_igdb_theme_by_id,
		get_igdb_themes_by_ids,
		get_igdb_website_by_id,
		get_igdb_websites_by_ids,
		get_sgdb_game_by_id,
		get_sgdb_game_by_platform,
		search_sgdb_games,
		get_sgdb_grids_by_game,
		get_sgdb_grids_by_platform,
		get_sgdb_heroes_by_game,
		get_sgdb_heroes_by_platform,
		get_sgdb_logos_by_game,
		get_sgdb_logos_by_platform,
		get_sgdb_icons_by_game,
		get_sgdb_icons_by_platform,
		list_ss_systems,
		get_ss_game_by_id,
		search_ss_games,
		get_ss_game_by_rom_name,
		list_mg_platforms,
		list_mg_genres,
		get_mg_game_by_id,
		search_mg_games,
		get_mg_game_covers,
		get_mg_game_screenshots,
		list_lb_platforms,
		get_lb_game_by_id,
		search_lb_games,
		get_lb_game_alternate_names,
		get_lb_game_images,
		get_ovgdb_release_by_id,
		get_ovgdb_rom_by_hash,
		list_ra_systems,
		get_ra_game_by_id,
		get_ra_game_by_hash,
		search_ra_games,
	),
	components(schemas(
		PageOfCompanyMetadataResponse,
		PageOfPlatformMetadataResponse,
		PageOfPlaymatchSignatureGroup,
		PageOfGameMetadataResponse,
		PageOfGameNameSearchResult,
		PageOfSuggestion,
		PageOfDatFileSummary,
		PageOfDatFileGame,
		PageOfDatFileImportTimelineEntry,
		PageOfPlaymatchGameFile,
		ServiceStats,
		PlatformStats,
		GameFilePresenceEntry,
		GameProviderMapping,
		CloneGraph,
		CloneGraphNode,
		CloneDirectionParam,
		DatFileSummary,
		DatFileDetail,
		DatFileGame,
		DatFilePresence,
		SignatureGroupPresence,
		DatFileImportRef,
		DatFileImportTimelineEntry,
		PresenceResult,
		ReverseLookupLevel,
		LatestDatFileImport,
		NamedRef,
		PageMeta,
		GameFileMatchSearch,
		BulkIdentifyRequest,
		BulkIdentifyItem,
		BulkIdentifySummary,
		BulkItemError,
		BulkItemStatus,
		BulkCache,
		BulkIdsRequest,
		BulkByIdSummary,
		BulkByIdStatusV2,
		BulkGamesByIdResult,
		BulkGamesByIdResponse,
		BulkPlatformsByIdResult,
		BulkPlatformsByIdResponse,
		BulkCompaniesByIdResult,
		BulkCompaniesByIdResponse,
		BulkDatFilesByIdResult,
		BulkDatFilesByIdResponse,
		BulkSignatureGroupsByIdResult,
		BulkSignatureGroupsByIdResponse,
		BulkGameFilesByIdResult,
		BulkGameFilesByIdResponse,
		BulkIdentifyIdsResult,
		BulkIdentifyIdsResponse,
		BulkIdentifyRelationsResult,
		BulkIdentifyRelationsResponse,
		V2ErrorBody,
		GameMetadataMatchResult,
		GameMetadataResponse,
		GameNameSearchResultV2,
		CompanyMetadataResponse,
		PlatformMetadataResponse,
		GameMatchType,
		ExternalMetadata,
		MetadataMatchType,
		ManualMatchMode,
		FailedMatchReason,
		MetadataProvider,
		AutomaticMatchReason,
		ExternalMetadataV2,
		AutomaticMatchReasonV2,
		AgeRating,
		AgeRatingCategory,
		AgeRatingContentDescriptionType,
		AgeRatingContentDescriptionV2,
		AgeRatingOrganization,
		AlternativeName,
		Artwork,
		ArtworkType,
		Character,
		CharacterGender,
		CharacterMugShot,
		CharacterSpecies,
		Collection,
		CollectionMembership,
		CollectionMembershipType,
		CollectionRelation,
		CollectionRelationType,
		CollectionType,
		Company,
		CompanyLogo,
		CompanySize,
		CompanyStatus,
		CompanyType,
		CompanyTypeHistory,
		CompanyWebsite,
		Cover,
		DateFormat,
		EntityType,
		Event,
		EventLogo,
		EventNetwork,
		ExternalGame,
		ExternalGameSource,
		Franchise,
		Game,
		GameEngine,
		GameEngineLogo,
		GameLocalization,
		GameMode,
		GameReleaseFormat,
		GameStatus,
		GameTimeToBeat,
		GameType,
		GameVersion,
		GameVersionFeature,
		GameVersionFeatureCategory,
		GameVersionFeatureValue,
		GameVersionFeatureValueEnum,
		GameVideo,
		Genre,
		InvolvedCompany,
		Keyword,
		Language,
		LanguageSupport,
		LanguageSupportType,
		MultiplayerMode,
		GameMatchRequest,
		CompanyOrPlatformMatchRequest,
		GameAndRelationMatchResultV2,
		GameAndRelationsResultV2,
		PlaymatchCompanyV2,
		PlaymatchGameV2,
		PlaymatchGameFileV2,
		PlaymatchPlatformV2,
		PlaymatchDatFileV2,
		PlaymatchDatFileImportV2,
		PlaymatchSignatureGroupV2,
		GameSuggestionRequest,
		CompanyOrPlatformSuggestionRequest,
		ExternalGameMatchSuggestionPayload,
		ExternalProviderMapping,
		UpdatedMetadataMatchesFromSuggestionResponse,
		Suggestion,
		User,
		UserPermissions,
		CreateOrGetUserRequestV2,
		UpdateUserPermissionsRequestV2,
		NetworkType,
		Platform,
		PlatformFamily,
		PlatformLogo,
		PlatformType,
		PlatformVersion,
		PlatformVersionCompany,
		PlatformVersionReleaseDate,
		PlatformWebsite,
		PlayerPerspective,
		PopularityPrimitive,
		PopularityType,
		Region,
		ReleaseDate,
		ReleaseDateRegion,
		ReleaseDateStatus,
		Report,
		ReportType,
		Screenshot,
		Theme,
		UpdatedMatchResult,
		Website,
		WebsiteType,
		SgdbGame,
		SgdbAsset,
		SgdbAuthor,
		SgdbPlatform,
		SgdbGridStyle,
		SgdbHeroStyle,
		SgdbLogoStyle,
		SgdbIconStyle,
		SgdbGridDimension,
		SgdbHeroDimension,
		SgdbAssetMime,
		SgdbAssetType,
		SgdbContentTag,
		SgdbTriState,
		AssetFilters,
		SgdbAssetFilterQuery,
		SsGame,
		SsLocalizedName,
		SsRom,
		SsSystem,
		SsSystemNames,
		SsEntityRef,
		MgGame,
		MgAltTitle,
		MgGamePlatformBrief,
		MgSampleCover,
		MgSampleScreenshot,
		MgPlatform,
		MgGenre,
		MgCover,
		MgCoverGroup,
		MgCoversResp,
		MgScreenshot,
		MgScreenshotsResp,
		LbGame,
		LbGameAlternateName,
		LbGameImage,
		LbPlatform,
		OvgdbRelease,
		OvgdbRom,
		OvgdbRomMatch,
		RaSystem,
		RaGame,
		RaGameHash,
		RaGameMatch
	))
)]
pub struct ApiDocV2;
