//! Playmatch server binary: loads the environment, then hands off to the api crate.

use dotenvy::dotenv;
use env_logger::Env;
use log::info;

pub mod built_info {
	// Generated by build.rs via the built crate.
	include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

fn main() {
	let _ = dotenv();
	env_logger::Builder::from_env(Env::default().default_filter_or("info")).init();

	info!(
		"Starting {} v{} ({}) built on {}",
		built_info::PKG_NAME,
		built_info::PKG_VERSION,
		built_info::GIT_COMMIT_HASH.unwrap_or("build commit unknown"),
		built_info::BUILT_TIME_UTC
	);

	api::main();
}
