[package]
name = "api"
version.workspace = true
edition.workspace = true
license = "MIT"

[dependencies]
entity = { path = "../entity" }
migration = { path = "../migration" }
service = { path = "../service" }
actix-cors = "^0.7"
actix-web = "^4"
actix-web-lab = "^0.26"
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["rustls-tls", "json", "cookies", "socks"] }
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "with-uuid"] }
chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_repr = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
actix-governor = "^0.10"
utoipa = { workspace = true, features = ["actix_extras", "uuid", "chrono", "repr", "debug"] }
utoipa-swagger-ui = { version = "~7", features = ["actix-web"] }
uuid = "^1.10"
derive_builder = { workspace = true }
tokio-cron-scheduler = "^0.15"
actix-web-prom = { version = "^0.10", features = ["process"] }
prometheus = { workspace = true }
redis = { workspace = true, features = ["tokio-rustls-comp"] }
