//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "company")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub name: String,
	pub updated_at: DateTimeWithTimeZone,
	pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::dat_file::Entity")]
	DatFile,
	#[sea_orm(has_many = "super::platform::Entity")]
	Platform,
	#[sea_orm(has_many = "super::signature_metadata_mapping::Entity")]
	SignatureMetadataMapping,
}

impl Related<super::dat_file::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::DatFile.def()
	}
}

impl Related<super::platform::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Platform.def()
	}
}

impl Related<super::signature_metadata_mapping::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::SignatureMetadataMapping.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
