//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod company;
pub mod dat_file;
pub mod dat_file_import;
pub mod game;
pub mod game_file;
pub mod game_file_presence;
pub mod launchbox_game;
pub mod launchbox_game_alternate_name;
pub mod launchbox_game_image;
pub mod launchbox_import;
pub mod launchbox_platform;
pub mod openvgdb_import;
pub mod openvgdb_release;
pub mod openvgdb_rom;
pub mod platform;
pub mod retroachievements_game;
pub mod retroachievements_game_hash;
pub mod retroachievements_import;
pub mod retroachievements_system;
pub mod sea_orm_active_enums;
pub mod signature_group;
pub mod signature_metadata_mapping;
pub mod signature_metadata_mapping_suggestions;
pub mod tgdb_game;
pub mod tgdb_game_alias;
pub mod user;
