//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::game_file::Entity as GameFile;
pub use super::game_release::Entity as GameRelease;
pub use super::game_release_id_mapping::Entity as GameReleaseIdMapping;
