//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12
//!
//! NOTE: `MetadataProviderEnum` has been hand-augmented with a `strum::EnumString`
//! derive (see below) so it can be parsed back from its sea-orm `string_value`
//! tag at runtime. If sea-orm-codegen is rerun against the schema, that derive
//! must be reapplied.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use strum::EnumString;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(
	rs_type = "String",
	db_type = "Enum",
	enum_name = "automatic_match_reason_enum"
)]
pub enum AutomaticMatchReasonEnum {
	#[sea_orm(string_value = "direct_name")]
	DirectName,
	#[sea_orm(string_value = "alternative_name")]
	AlternativeName,
	#[sea_orm(string_value = "via_child")]
	ViaChild,
	#[sea_orm(string_value = "via_parent")]
	ViaParent,
	#[sea_orm(string_value = "normalized_name")]
	NormalizedName,
	#[sea_orm(string_value = "normalized_alternative_name")]
	NormalizedAlternativeName,
	#[sea_orm(string_value = "md5_hash")]
	Md5Hash,
	#[sea_orm(string_value = "sha1_hash")]
	Sha1Hash,
	#[sea_orm(string_value = "crc_hash")]
	CrcHash,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(
	rs_type = "String",
	db_type = "Enum",
	enum_name = "failed_match_reason_enum"
)]
pub enum FailedMatchReasonEnum {
	#[sea_orm(string_value = "no_direct_match")]
	NoDirectMatch,
	#[sea_orm(string_value = "too_many_matches")]
	TooManyMatches,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(
	rs_type = "String",
	db_type = "Enum",
	enum_name = "manual_match_mode_enum"
)]
pub enum ManualMatchModeEnum {
	#[sea_orm(string_value = "admin")]
	Admin,
	#[sea_orm(string_value = "trusted")]
	Trusted,
	#[sea_orm(string_value = "community")]
	Community,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "match_type_enum")]
pub enum MatchTypeEnum {
	#[sea_orm(string_value = "none")]
	None,
	#[sea_orm(string_value = "automatic")]
	Automatic,
	#[sea_orm(string_value = "manual")]
	Manual,
	#[sea_orm(string_value = "failed")]
	Failed,
}
#[derive(
	Debug,
	Clone,
	PartialEq,
	Eq,
	EnumIter,
	DeriveActiveEnum,
	Copy,
	Serialize,
	Deserialize,
	EnumString,
)]
#[sea_orm(
	rs_type = "String",
	db_type = "Enum",
	enum_name = "metadata_provider_enum"
)]
#[strum(serialize_all = "snake_case", ascii_case_insensitive)]
pub enum MetadataProviderEnum {
	#[sea_orm(string_value = "igdb")]
	Igdb,
	#[sea_orm(string_value = "steamgriddb")]
	Steamgriddb,
	#[sea_orm(string_value = "screenscraper")]
	Screenscraper,
	#[sea_orm(string_value = "mobygames")]
	Mobygames,
	#[sea_orm(string_value = "launchbox")]
	Launchbox,
	#[sea_orm(string_value = "emuready")]
	EmuReady,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(
	rs_type = "String",
	db_type = "Enum",
	enum_name = "user_permissions_enum"
)]
pub enum UserPermissionsEnum {
	#[sea_orm(string_value = "user")]
	User,
	#[sea_orm(string_value = "trusted")]
	Trusted,
	#[sea_orm(string_value = "automation")]
	Automation,
	#[sea_orm(string_value = "admin")]
	Admin,
}
