//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "game_release_provider_enum"
)]
pub enum GameReleaseProviderEnum {
    #[sea_orm(string_value = "no_intro")]
    NoIntro,
    #[sea_orm(string_value = "redump")]
    Redump,
}
