//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub id: Uuid,
	pub name: String,
	pub discord_id: String,
	pub created_at: DateTimeWithTimeZone,
	pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::signature_metadata_mapping::Entity")]
	SignatureMetadataMapping,
}

impl Related<super::signature_metadata_mapping::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::SignatureMetadataMapping.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
